version: '3'

# Other services are specified in .\lib\killrvideo-docker-common\docker-compose.yaml
services:
  # Start the service implementation of your choice (Java, C#, node.js) separately

  # The sample data generator
  generator:
    image: killrvideo/killrvideo-generator:1.2.3
    depends_on:
    - dse
    - etcd
    environment:
      KILLRVIDEO_ETCD: "etcd:2379"
      KILLRVIDEO_DSE_USERNAME: $KILLRVIDEO_DSE_USERNAME
      KILLRVIDEO_DSE_PASSWORD: $KILLRVIDEO_DSE_PASSWORD
      NODE_ENV: $NODE_ENV
      KILLRVIDEO_CASSANDRA_REPLICATION: $KILLRVIDEO_CASSANDRA_REPLICATION
      KILLRVIDEO_LOGGING_LEVEL: $KILLRVIDEO_LOGGING_LEVEL

