# Allow configuration in YAML files to be overridden by environment variable values
loggingLevel: KILLRVIDEO_LOGGING_LEVEL

client:
  youTubeApiKey: KILLRVIDEO_YOUTUBE_API_KEY

web:
  session:
    secret: KILLRVIDEO_SESSION_SECRET